version: "3.9"
services:
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/user/src/app
    container_name: frontend
    depends_on:
      - spotifytool

  spotifytool:
    build: ./spotifytool
    ports:
      - "8080:8080"
    volumes:
      - ./spotifytool:/target/spotifytool-0.0.1-SNAPSHOT.jar:/app.jar
    container_name: backend



    


  